# Generated by Django 2.1.2 on 2018-10-30 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stax_official', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='name',
            name='email',
        ),
    ]
