# Generated by Django 2.1.2 on 2018-11-05 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stax_official', '0003_auto_20181105_1320'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Name',
            new_name='Query',
        ),
    ]
