# Generated by Django 2.1.2 on 2018-11-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stax_official', '0004_auto_20181105_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='section',
        ),
        migrations.AddField(
            model_name='tag',
            name='section',
            field=models.ManyToManyField(to='stax_official.Section'),
        ),
    ]
